name: smartcadd-test
channels:
    - conda-forge
    - dglteam
    - defaults
dependencies:
    - python>=3.10
    - pip
    - jupyter
    - pymol-open-source
    - h5py
    - openbabel
    - pdbfixer
    - rdkit
    - numpy
    - pandas
    - xtb
    - pip:
          - deepchem
          - openmm
          - mdanalysis
          - pybel
          - torch
          - torchdata
          - dgl==1.1.2
          - dgllife

